version: '3.7'
networks:
  xeda-local:
    external: true
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - xeda-local

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka
    ports:
     - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    links:
      - zookeeper
    networks:
      - xeda-local

  kafka-manager:
    image: zenko/kafka-manager:1.3.3.22
    container_name: kafka-manager
    ports:
    - "9000:9000"
    depends_on:
    - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
    links:
      - zookeeper
      - kafka
    networks:
    - xeda-local

  kafka-pixy:
    container_name: kafka-pixy
    image: mailgun/kafka-pixy:latest
    restart: on-failure
    volumes:
    - ./target/3rd/integration-tests-utils/config/kafka-pixy.yaml:/etc/kafka-pixy.yaml
    command: --config /etc/kafka-pixy.yaml
    ports:
    - "19091:19091"
    - "19092:19092"
    depends_on:
    - kafka
    networks:
    - xeda-local