version: '3.7'
networks:
  xeda-local:
    external: true
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - xeda-local

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka
    ports:
     - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    links:
      - zookeeper
    networks:
      - xeda-local

  kafka-pixy:
    container_name: kafka-pixy
    image: mailgun/kafka-pixy:latest
    restart: on-failure
    volumes:
    - ./bin/integration-tests-utils/config/kafka-pixy.yaml:/etc/kafka-pixy.yaml
    command: --config /etc/kafka-pixy.yaml
    ports:
    - "19091:19091"
    - "19092:19092"
    depends_on:
    - kafka
    networks:
    - xeda-local

  mongodb:
    image: docker.io/mongo:4.0.12
    container_name: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./data-mongo/db:/data/db
    ports:
      - 27017:27017
    command: mongod
    networks:
      - xeda-local

  mysql-activiti:
    container_name: mysql-activiti
    build:
      context: target/3rd/mysql-activiti
      dockerfile: ./Dockerfile
    image: mysql-activiti:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=#0r4ng3X
      - ACTIVITI_USER_PASSWORD=4ct1v1t1
      - ACTIVITI_ADMIN_USER_PASSWORD=4ct1v1t1
    networks:
      - xeda-local

  xeda-kafka-schemas:
    container_name: xeda-kafka-schemas
    build:
      context: target/3rd/xeda-kafka-schemas
      dockerfile: ./Dockerfile
    image: xeda-kafka-schemas:latest
    restart: on-failure
    ports:
      - "8081:8080"
    networks:
      - xeda-local

  event-handler-generic:
    container_name: event-handler-generic
    build:
      context: target/3rd/event-handler-generic
      dockerfile: ./Dockerfile
    image: event-handler-generic:latest
    restart: on-failure
    environment:
      KAFKA_HOST: kafka:9092
      SCHEMA_SERVER_HOST: http://xeda-kafka-schemas:8080
      MONGODB_USER: admin
      MONGODB_PASSWORD: admin
      MONGO_HOST: mongodb:27017
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
      - kafka
      - xeda-kafka-schemas
    networks:
      - xeda-local

  xbyorange-finder:
    container_name: xbyorange-finder
    build:
      context: target/3rd/xbyorange-finder
      dockerfile: ./Dockerfile
    image: xbyorange-finder:latest
    restart: on-failure
    ports:
      - "8084:8080"
    environment:
      MONGODB_USER: admin
      MONGODB_PASSWORD: admin
      MONGO_HOST: mongodb:27017
    depends_on:
      - mongodb
    networks:
      - xeda-local